spring:
  datasource:
    url: jdbc:mysql://112.74.172.75:3306/db_gz_lss?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=GMT
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  thymeleaf:
    cache: false
  messages:
    basename: static/messages/messages
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 2000
mybatis:
  type-aliases-package: com.gz.lss.pojo
logging:
  level:
    com.gz.lss.dao: debug
